"""initial migration

Revision ID: dbd79558889c
Revises: 36b5774d0b57
Create Date: 2026-02-18 12:32:19.777897

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dbd79558889c'
down_revision: Union[str, None] = '36b5774d0b57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('qdrantidss',
    sa.Column('ids', sa.Uuid(), nullable=False),
    sa.Column('table_name', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('children')
    op.drop_table('schools')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schools',
    sa.Column('schoolid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('schoolname', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('area', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('government', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('ootype', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('schooltype', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('schoolkind', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('towntype', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('ownertype', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('teachercnt', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('partcnt', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('avgpower', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('cntpower', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('cnt9', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('cnt11', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('avgmath9', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('avgmath11', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('avgrus9', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('avgrus11', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('cnt2rus9', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('cnt2mat9', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('cnt2rus11', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('cnt2mat11', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('schoolid', name=op.f('schools_pkey'))
    )
    op.create_table('children',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('schoolboy_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('school_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['school_id'], ['schools.schoolid'], name=op.f('fk_school')),
    sa.PrimaryKeyConstraint('id', name=op.f('table_name_pkey'))
    )
    op.drop_table('qdrantidss')
    # ### end Alembic commands ###
